#!/bin/sh
# index.html is generated by concatenating build/* in order.
set -e
cd "$(dirname "$0")"
cat build/01-shell.html \
    build/02-core.js \
    build/02b-plates.js \
    build/03-render.js \
    build/03b-paint.js \
    build/04-life.js \
    build/05-sound.js \
    build/06-scenes-a.js \
    build/06b-plate-scenes.js \
    build/07-scenes-b.js \
    build/08-scenes-c.js \
    build/09-evidence.js \
    build/10-finale.js \
    build/11-director.js > index.html
printf '</script>\n</body>\n</html>\n' >> index.html
echo "built index.html ($(wc -l < index.html) lines)"
